env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - import

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  '@typescript-eslint/explicit-module-boundary-types': off
  import/no-unresolved: 2
  import/order:
    [
      'error',
      {
        'newlines-between': 'always',
        'groups': ['builtin', 'external', 'internal'],
      },
    ]
