name: Publish Storybook to GitHub Pages

on:
  push:
    branches: ['master']

jobs:
  deploy-storybook:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Deploy Storybook
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
            cache: 'yarn'
        - run: yarn install --frozen-lockfile;
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: ${{ github.ref == 'refs/heads/main' }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./storybook-static